#!/bin/sh

mkdir -p ~/.config

link () {
  if [ ! -e $2 ]; then
    ln -s $1 $2
  fi
}

link ~/.dotfiles/config/alacritty ~/.config/alacritty
link ~/.dotfiles/config/iterm2 ~/.config/iterm2
link ~/.dotfiles/config/nvim ~/.config/nvim
link ~/.dotfiles/config/tmux ~/.config/tmux

link ~/.dotfiles/tmux.conf ~/.tmux.conf
link ~/.dotfiles/zfunctions ~/.zfunctions
link ~/.dotfiles/zprofile ~/.zprofile
link ~/.dotfiles/zshrc ~/.zshrc
link ~/.dotfiles/zshenv ~/.zshenv
link ~/.dotfiles/secrets ~/.secrets

link ~/.config/nvim/init.vim ~/.nvimrc
